-- For conciseness
local opts = { noremap = true, silent = true }
--
-- -- Set <space> as the leader key
-- -- See `:help mapleader`
-- --  NOTE: Must happen before plugins are loaded (otherwise wrong leader will be used)
vim.g.mapleader = " "
vim.g.maplocalleader = " "
--
-- Clear highlights on search when pressing <Esc> in normal mode
--  See `:help hlsearch`
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
--
-- -- Diagnostic keymaps
-- vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
--
-- -- Exit terminal mode in the builtin terminal with a shortcut that is a bit easier
-- -- for people to discover. Otherwise, you normally need to press <C-\><C-n>, which
-- -- is not what someone will guess without a bit more experience.
-- --
-- -- NOTE: This won't work in all terminal emulators/tmux/etc. Try your own mapping
-- -- or just use <C-\><C-n> to exit terminal mode
-- vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
--
-- -- Disable the spacebar key's default behavior in Normal and Visual modes
-- vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { silent = true })
--
-- -- Keybinds to make split navigation easier.
-- --  Use CTRL+<hjkl> to switch between windows
-- --
-- --  See `:help wincmd` for a list of all window commands
-- vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
-- vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
-- vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
-- vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
--
-- -- Resize with arrows
-- vim.keymap.set("n", "<Up>", ":resize +2<CR>", opts)
-- vim.keymap.set("n", "<Down>", ":resize -2<CR>", opts)
-- vim.keymap.set("n", "<Left>", ":vertical resize +2<CR>", opts)
-- vim.keymap.set("n", "<Right>", ":vertical resize -2<CR>", opts)
--
-- -- save file
-- vim.keymap.set("n", "<C-s>", "<cmd> w <CR>", opts)
--
-- -- save file without auto-formatting
-- vim.keymap.set("n", "<leader>sn", "<cmd>noautocmd w <CR>", opts)
--
-- -- quit file
-- vim.keymap.set("n", "<C-q>", "<cmd> q <CR>", opts)
--
-- -- delete single character without copying into register
-- vim.keymap.set("n", "x", '"_x', opts)
--
-- -- Vertical scroll and center
-- vim.keymap.set("n", "<C-d>", "<C-d>zz", opts)
-- vim.keymap.set("n", "<C-u>", "<C-u>zz", opts)
--
-- -- Find and center
-- vim.keymap.set("n", "n", "nzzzv")
-- vim.keymap.set("n", "N", "Nzzzv")
--
-- Buffers
vim.keymap.set("n", "<Tab>", ":bnext<CR>", opts)
vim.keymap.set("n", "<S-Tab>", ":bprevious<CR>", opts)
vim.keymap.set("n", "<C-i>", "<C-i>", opts) -- to restore jump forward
vim.keymap.set("n", "<leader>x", ":Bdelete!<CR>", opts) -- close buffer
vim.keymap.set("n", "<leader>b", "<cmd> enew <CR>", opts) -- new buffer
--
-- -- Window management
-- vim.keymap.set("n", "<leader>v", "<C-w>v", { desc = "Split window vertically" }) -- split window vertically
-- vim.keymap.set("n", "<leader>h", "<C-w>s", { desc = "Split window horizontally" }) -- split window horizontally
-- vim.keymap.set("n", "<leader>se", "<C-w>=", { desc = "Make [S]plits [E]qual" }) -- make split windows equal width & height
-- vim.keymap.set("n", "<leader>xs", ":close<CR>", { desc = "Close current split window" }) -- close current split window
--
-- -- Navigate between splits
-- vim.keymap.set("n", "<C-k>", ":wincmd k<CR>", { desc = "Move up split" })
-- vim.keymap.set("n", "<C-j>", ":wincmd j<CR>", { desc = "Move down split" })
-- vim.keymap.set("n", "<C-h>", ":wincmd h<CR>", { desc = "Move left split" })
-- vim.keymap.set("n", "<C-l>", ":wincmd l<CR>", { desc = "Move right split" })
--
-- -- Stay in indent mode
-- vim.keymap.set("v", "<", "<gv", opts)
-- vim.keymap.set("v", ">", ">gv", opts)
--
-- -- -- Move selected text up and down without changing indentation
-- -- vim.keymap.set('v', '<A-j>', ":m '>+1<CR>gv", opts)
-- -- vim.keymap.set('v', '<A-k>', ":m '<-2<CR>gv", opts)
-- --
-- -- -- Move text up and down
-- -- vim.keymap.set('v', '<A-j>', ':m .+1<CR>==', opts)
-- -- vim.keymap.set('v', '<A-k>', ':m .-2<CR>==', opts)
--
-- -- Keep last yanked when pasting
-- vim.keymap.set("v", "p", '"_dP', opts)
--
-- -- Replace word under cursor
-- vim.keymap.set("n", "<leader>j", "*``cgn", opts)
--
-- -- Open Lazy.nvim
-- vim.keymap.set("n", "<leader>L", "<cmd> Lazy <CR>", opts)
