-- -- Set kitty terminal padding to 0 when in nvim
-- vim.cmd([[
--   augroup kitty_mp
--   autocmd!
--   au VimLeave * :silent !kitty @ set-spacing padding=default margin=default
--   au VimEnter * :silent !kitty @ set-spacing padding=0 margin=0 3 0 3
--   augroup END
-- ]])
--
-- -- Highlight when yanking (copying) text
-- --  Try it with `yap` in normal mode
-- --  See `:help vim.hl.on_yank()`
-- vim.api.nvim_create_autocmd("TextYankPost", {
-- 	desc = "Highlight when yanking (copying) text",
-- 	group = vim.api.nvim_create_augroup("kickstart-highlight-yank", { clear = true }),
-- 	callback = function()
-- 		vim.hl.on_yank()
-- 	end,
-- })
